@api = http://localhost:3000/api

### POST signup
POST {{api}}/auth/signup
Content-Type: application/json

{
  "name": "Santiago",
  "email": "santiagodavidlopezbenavides@gmail.com",
  "password": "password"
}

### POST signin
POST {{api}}/auth/signIn
Content-Type: application/json

{
  "email": "santiagodavidlopezbenavides@gmail.com",
  "password": "password"
}

### POST code
POST {{api}}/auth/code
Content-Type: application/json

{
  "email": "santiagodavidlopezbenavides@gmail.com"
}

### GET code
GET {{api}}/auth/code
Content-Type: application/json

{
  "email": "santiagodavidlopezbenavides@gmail.com",
  "code": "a800ee"
}

### POST password
POST {{api}}/auth/password
Content-Type: application/json

{
  "email": "santiagodavidlopezbenavides@gmail.com",
  "code": "a800ee",
  "password": "password"
}

### GET user
GET {{api}}/auth/user
Content-Type: application/json
Authorization: Bearer asdasasdasd.asdasda.asd

{
  
}